### ISSUE TITLE
How to Implement Two Metrics in Tibber Exporter?

### ISSUE THREAD

**Issue by mario-2015** [terjesannum/tibber-exporter#16]
Hello,

I'm encountering an issue with the Tibber Exporter where it seems to be attempting to register duplicate metrics collectors. I have two meters operating with two separate contracts, one for household usage and another for a heat pump. Below is the log output indicating the error:

[Log Output]
```
2024/01/29 19:23:29 Starting tibber-exporter/3.6.3 (https://github.com/terjesannum/tibber-exporter)
2024/01/29 19:23:29 Websocket url: wss://websocket-api.tibber.com/v1-beta/gql/subscriptions
2024/01/29 19:23:29 Found home: XXXXXXXXX-b5fe-XXXXXXX-9805-XXXXXXXX - Haushalt
2024/01/29 19:23:29 Starting monitoring of home: XXXXXXXXXXX-b5fe-XXXXXX-9805-XXXXXXXXXX - Haushalt
2024/01/29 19:23:29 Current subscription: XXXXXXX-ee09-XXXXXXX-83a2-XXXXXXXX
2024/01/29 19:23:29 Creating home collector for home XXXXXXXXX-b5fe-XXXXXX-9805-XXXXXXXXXXX
2024/01/29 19:23:29 Realtime consumption enabled for XXXXXXXXX-b5fe-XXXXXX-9805-XXXXXXXXXXX: true
2024/01/29 19:23:29 Starting live measurements monitoring of home XXXXXXX-b5fe-XXXXX-9805-XXXXXXX
2024/01/29 19:23:29 Live feed timeout: 1 minute
2024/01/29 19:23:29 Updating prices for XXXXXXX-b5fe-XXXXX-9805-XXXXXXXXXXXX
2024/01/29 19:23:29 Creating measurements subscription for home XXXXX-b5fe-XXXXXXX-9805-XXXXXXXX
2024/01/29 19:23:29 Starting subscription XXXXXXX-d5bf-XXXXX-9256-XXXXXXX for home XXXXXX-b5fe-XXXXX-9805-XXXXXXX
2024/01/29 19:23:29 Found home: XXXXXX-3fe5-XXXXXXX-8fa6-XXXXXXXXXXXX - Wärmepumpe
2024/01/29 19:23:29 Starting monitoring of home: XXXXXX-3fe5-XXXX-8fa6-XXXXXXX - Wärmepumpe
2024/01/29 19:23:29 Current subscription: XXXXXX-a137-XXXXX-a7a0-XXXXXXXXXXX
panic: duplicate metrics collector registration attempted

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0x917fa6?, {0xc0001de160?, 0x1, 0xc0004afe10?})
	/go/pkg/mod/github.com/prometheus/client_golang@v1.17.0/prometheus/registry.go:405 +0x78
github.com/prometheus/client_golang/prometheus.MustRegister(...)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.17.0/prometheus/registry.go:177
main.main()
	/workspace/main.go:143 +0xde2

```

Is there a way to split or filter the metrics for each meter to avoid this conflict? Any guidance on handling multiple meters in a single Tibber Exporter instance would be greatly appreciated.

Thank you.

**Comment by terjesannum** [comment]
Clearly a bug, thanks for reporting. Try version 3.6.4 and see if that fixes the problem.

**Comment by mario-2015** [comment]
I've checked and rebuilt with version 3.6.4, and it works now! 👍 Thank you so much for the prompt support and for providing the update!

**Comment by mario-2015** [comment]
👍 Thank you
